[package]
name = "jpdict"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
once_cell = "1.19.0"