[package]
name = "jpdict"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.27.0", features = ["bundled"] }